// Import project images
import aizelInterior1 from '../images/projects/aizel-interior-1.jpg';
import aizelInterior2 from '../images/projects/aizel-interior-2.jpg';
import aizelWarsan1 from '../images/projects/aizel-warsan-1.jpg';
import aizelWarsan2 from '../images/projects/aizel-warsan-2.jpg';
import maakResidence1 from '../images/projects/maak-residence-1.jpg';
import maakResidence2 from '../images/projects/maak-residence-2.jpg';

const Projects = [
    {
       Id:'1',
       pImg: maakResidence1,
       ps1img: maakResidence1,
       psub1img1: maakResidence2,
       psub1img2: maakResidence1,
       title:'Maak Residence Dubai South',  
       subTitle:'Luxury Residential Development',   
       description: 'A premium residential development in Dubai South featuring modern architecture and luxurious amenities.',
       category: 'Residential',
       location: 'Dubai South, UAE',
       area: '25,000 sq ft',
       status: 'Under Construction'
    },
    {
       Id:'2',
       pImg: aizelWarsan1,
       ps1img: aizelWarsan1,
       psub1img1: aizelWarsan2,
       psub1img2: aizelWarsan1,
       title:'Aizel Tower Warsan', 
       subTitle:'Commercial Tower Development',    
       description: 'A state-of-the-art commercial tower in Warsan featuring contemporary design and sustainable building practices.',
       category: 'Commercial',
       location: 'Warsan, Dubai, UAE',
       area: '45,000 sq ft',
       status: 'Completed'
    },
    {
      Id:'3',
      pImg: aizelInterior1,
      ps1img: aizelInterior1,
      psub1img1: aizelInterior2,
      psub1img2: aizelInterior1,
      title:'Aizel Tower Interior',  
      subTitle:'Interior Design & Fit-out',   
      description: 'Comprehensive interior design and fit-out services for the Aizel Tower, creating modern and functional spaces.',
      category: 'Interior Design',
      location: 'Warsan, Dubai, UAE',
      area: '35,000 sq ft',
      status: 'In Progress'
   },
    {
       Id:'4',
       pImg: maakResidence2,
       ps1img: maakResidence2,
       psub1img1: maakResidence1,
       psub1img2: maakResidence2,
       title:'Maak Residence - Phase 2',  
       subTitle:'Residential Complex Extension', 
       description: 'Second phase of the Maak Residence development, expanding the luxury residential complex.',
       category: 'Residential',
       location: 'Dubai South, UAE',
       area: '30,000 sq ft',
       status: 'Planning'
    },
    {
       Id:'5',
       pImg: maakResidence1,
       ps1img: maakResidence1,
       psub1img1: maakResidence2,
       psub1img2: maakResidence1,
       title:'Maak Residence - Amenities',  
       subTitle:'Recreational Facilities',   
       description: 'Design and construction of recreational facilities and amenities for the Maak Residence development.',
       category: 'Amenities',
       location: 'Dubai South, UAE',
       area: '15,000 sq ft',
       status: 'Under Construction'
    },
    {
       Id:'6',
       pImg: aizelInterior2,
       ps1img: aizelInterior2,
       psub1img1: aizelInterior1,
       psub1img2: aizelInterior2,
       title:'Aizel Tower - Lobby Design', 
       subTitle:'Grand Entrance & Reception',    
       description: 'Design and construction of the grand lobby and reception area for the Aizel Tower.',
       category: 'Interior Design',
       location: 'Warsan, Dubai, UAE',
       area: '8,000 sq ft',
       status: 'Completed'
    },
    {
      Id:'7',
      pImg: aizelInterior1,
      ps1img: aizelInterior1,
      psub1img1: aizelInterior2,
      psub1img2: aizelInterior1,
      title:'Aizel Tower - Office Spaces', 
      subTitle:'Modern Office Interiors',  
      description: 'Design and fit-out of modern office spaces within the Aizel Tower.',
      category: 'Interior Design',
      location: 'Warsan, Dubai, UAE',
      area: '20,000 sq ft',
      status: 'In Progress'
   },
    {
       Id:'8',
       pImg: aizelInterior2,
       ps1img: aizelInterior2,
       psub1img1: aizelInterior1,
       psub1img2: aizelInterior2,
       title:'Aizel Tower - Common Areas', 
       subTitle:'Shared Spaces Design',
       description: 'Design and construction of common areas and shared spaces in the Aizel Tower.',
       category: 'Interior Design',
       location: 'Warsan, Dubai, UAE',
       area: '12,000 sq ft',
       status: 'Completed'
    },
    {
       Id:'9',
       pImg: maakResidence2,
       ps1img: maakResidence2,
       psub1img1: maakResidence1,
       psub1img2: maakResidence2,
       title:'Maak Residence - Landscaping',  
       subTitle:'Garden & Outdoor Design', 
       description: 'Landscape design and outdoor space planning for the Maak Residence development.',
       category: 'Landscaping',
       location: 'Dubai South, UAE',
       area: '18,000 sq ft',
       status: 'Planning'
    },
    {
      Id:'10',
      pImg: aizelInterior1,
      ps1img: aizelInterior1,
      psub1img1: aizelInterior2,
      psub1img2: aizelInterior1,
      title:'Aizel Tower - Retail Spaces',  
      subTitle:'Commercial Interior Design',   
      description: 'Design and fit-out of retail and commercial spaces in the Aizel Tower.',
      category: 'Interior Design',
      location: 'Warsan, Dubai, UAE',
      area: '25,000 sq ft',
      status: 'In Progress'
   },
   {
      Id:'11',
      pImg: maakResidence1,
      ps1img: maakResidence1,
      psub1img1: maakResidence2,
      psub1img2: maakResidence1,
      title:'Maak Residence - Parking', 
      subTitle:'Underground Parking Design',    
      description: 'Design and construction of underground parking facilities for the Maak Residence.',
      category: 'Infrastructure',
      location: 'Dubai South, UAE',
      area: '40,000 sq ft',
      status: 'Under Construction'
   },
   {
     Id:'12',
     pImg: aizelWarsan2,
     ps1img: aizelWarsan2,
     psub1img1: aizelWarsan1,
     psub1img2: aizelWarsan2,
     title:'Aizel Tower - Exterior',  
     subTitle:'Facade & Building Envelope',   
     description: 'Design and construction of the building facade and exterior envelope for the Aizel Tower.',
     category: 'Architecture',
     location: 'Warsan, Dubai, UAE',
     area: '50,000 sq ft',
     status: 'Completed'
  },
   {
     Id:'13',
     pImg: maakResidence2,
     ps1img: maakResidence2,
     psub1img1: maakResidence1,
     psub1img2: maakResidence2,
     title:'Maak Residence - Security',  
     subTitle:'Security Systems Integration',   
     description: 'Integration of security systems and access control for the Maak Residence development.',
     category: 'Security',
     location: 'Dubai South, UAE',
     area: '25,000 sq ft',
     status: 'In Progress'
  },
   {
     Id:'14',
     pImg: aizelInterior1,
     ps1img: aizelInterior1,
     psub1img1: aizelInterior2,
     psub1img2: aizelInterior1,
     title:'Aizel Tower - HVAC',  
     subTitle:'Mechanical Systems',   
     description: 'Design and installation of HVAC and mechanical systems for the Aizel Tower.',
     category: 'MEP',
     location: 'Warsan, Dubai, UAE',
     area: '45,000 sq ft',
     status: 'Completed'
  },
   {
     Id:'15',
     pImg: maakResidence1,
     ps1img: maakResidence1,
     psub1img1: maakResidence2,
     psub1img2: maakResidence1,
     title:'Maak Residence - Electrical',  
     subTitle:'Electrical Systems Design',   
     description: 'Design and installation of electrical systems and lighting for the Maak Residence.',
     category: 'MEP',
     location: 'Dubai South, UAE',
     area: '25,000 sq ft',
     status: 'Under Construction'
  },
   {
     Id:'16',
     pImg: aizelInterior2,
     ps1img: aizelInterior2,
     psub1img1: aizelInterior1,
     psub1img2: aizelInterior2,
     title:'Aizel Tower - Fire Safety',  
     subTitle:'Fire Protection Systems',   
     description: 'Design and installation of fire safety and protection systems for the Aizel Tower.',
     category: 'Safety',
     location: 'Warsan, Dubai, UAE',
     area: '45,000 sq ft',
     status: 'Completed'
  },
   {
     Id:'17',
     pImg: aizelInterior1,
     ps1img: aizelInterior1,
     psub1img1: aizelInterior2,
     psub1img2: aizelInterior1,
     title:'Aizel Tower - Smart Systems',  
     subTitle:'Building Automation',   
     description: 'Integration of smart building systems and automation for the Aizel Tower.',
     category: 'Technology',
     location: 'Warsan, Dubai, UAE',
     area: '45,000 sq ft',
     status: 'In Progress'
  },
   {
     Id:'18',
     pImg: maakResidence2,
     ps1img: maakResidence2,
     psub1img1: maakResidence1,
     psub1img2: maakResidence2,
     title:'Maak Residence - Sustainability',  
     subTitle:'Green Building Features',    
     description: 'Implementation of sustainable and green building features for the Maak Residence development.',
     category: 'Sustainability',
     location: 'Dubai South, UAE',
     area: '25,000 sq ft',
     status: 'Planning'
  },
    
]

export default Projects;